# Generated by Django 3.0.7 on 2022-06-16 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='access_stars',
            new_name='accessStars',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='congestion_degree',
            new_name='congestionDegree',
        ),
        migrations.RemoveField(
            model_name='post',
            name='created_on',
        ),
    ]
