version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn server.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - db
   

  db:
    image: mysql:5.7.22
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - .dbdate:/var/lib/mysql
      - './mysql/etc/my.cnf:/etc/my.cnf'
    ports: 
      - 3306:3306

  front:
    build:
      context: .
      dockerfile: Dockerfile_react
    restart: always
    volumes:
      - ./node:/usr/src/app:cached
    command: sh -c "cd front && yarn start"
    ports:
      - "3000:3000"
    