version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: gunicorn server.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    depends_on: 
      - db

  backend-server:
    build:
      context: ./backend/nginx/.
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:5.7.38
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - ./backend/.dbdate:/var/lib/mysql
      - './backend/mysql/etc/my.cnf:/etc/my.cnf'
    ports: 
      - 3306:3306
    
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
    tty: true
    ports:
      - "3000:3000"
    command: npm run dev