version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn server.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - db
   

  db:
    image: mysql:5.7.22
    restart: always
    environment: 
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
   
    volumes: 
      - .dbdate:/var/lib/mysql
      - './mysql/etc/my.cnf:/etc/my.cnf'
    ports: 
      - 3306:3306

  front:
    build:
      context: ./node/front
      dockerfile: Dockerfile_react.prod
    volumes:
      - react_build:/node/build
    ports:
      - "3000:3000"

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/node
    depends_on:
      - backend
      - front
volumes:
  react_build: