version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: gunicorn server.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on: 
      - db

  backend-server:
    build:
      context: ./nginx/.
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:5.7.38
    restart: always
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes: 
      - .dbdate:/var/lib/mysql
      - './mysql/etc/my.cnf:/etc/my.cnf'
    ports: 
      - 3306:3306